//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Free_Spotify.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ja_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ja_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Free_Spotify.Localization.Localization.ja-", typeof(Localization_ja_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточна версія:.
        /// </summary>
        internal static string AppCurrentVersionDefaultText {
            get {
                return ResourceManager.GetString("AppCurrentVersionDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артист:.
        /// </summary>
        internal static string ArtistDefaultText {
            get {
                return ResourceManager.GetString("ArtistDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коли вікно згорнуто, під час перемикання пісні спливатиме плеєр, який можна налаштувати як завгодно..
        /// </summary>
        internal static string BallonPlayerCheckBoxToolTip {
            get {
                return ResourceManager.GetString("BallonPlayerCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спливаюче вікно програвача:.
        /// </summary>
        internal static string BallonPlayerText {
            get {
                return ResourceManager.GetString("BallonPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірити оновлення.
        /// </summary>
        internal static string CheckUpdatesMenuItemHeader {
            get {
                return ResourceManager.GetString("CheckUpdatesMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нічого не робить....
        /// </summary>
        internal static string DiscordRPCAFK {
            get {
                return ResourceManager.GetString("DiscordRPCAFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слухає музику....
        /// </summary>
        internal static string DiscordRPCListeningTo {
            get {
                return ResourceManager.GetString("DiscordRPCListeningTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Послухати трек....
        /// </summary>
        internal static string DiscordRPCListenToTrack {
            get {
                return ResourceManager.GetString("DiscordRPCListenToTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставив музику на паузу....
        /// </summary>
        internal static string DiscordRPCPausedTrack {
            get {
                return ResourceManager.GetString("DiscordRPCPausedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схоже у вас проблеми з інтернетом!.
        /// </summary>
        internal static string ErrorNoInternetText {
            get {
                return ResourceManager.GetString("ErrorNoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По запиту:.
        /// </summary>
        internal static string ErrorNothingFoundText {
            get {
                return ResourceManager.GetString("ErrorNothingFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нічого не знайдено..
        /// </summary>
        internal static string ErrorNothingFoundText1 {
            get {
                return ResourceManager.GetString("ErrorNothingFoundText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова:.
        /// </summary>
        internal static string LanguageSettingsDefaultText {
            get {
                return ResourceManager.GetString("LanguageSettingsDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що хочете послухати?.
        /// </summary>
        internal static string SearchBarTextBoxDefaultText {
            get {
                return ResourceManager.GetString("SearchBarTextBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошукова система:.
        /// </summary>
        internal static string SearchEngineLabelText {
            get {
                return ResourceManager.GetString("SearchEngineLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Якщо ви не можете знайти трек, який є в YouTube, ви можете спокійно поміняти пошукову систему і насолоджуватися музикою з YouTube..
        /// </summary>
        internal static string SearchEngineToolTipText {
            get {
                return ResourceManager.GetString("SearchEngineToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string SettingsMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомий Артист.
        /// </summary>
        internal static string SongAuthorDefaultText {
            get {
                return ResourceManager.GetString("SongAuthorDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомий трек.
        /// </summary>
        internal static string SongTitleDefaultText {
            get {
                return ResourceManager.GetString("SongTitleDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почніть писати щось, щоб насолоджуватися піснями!.
        /// </summary>
        internal static string TipStartWrittingText {
            get {
                return ResourceManager.GetString("TipStartWrittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трек:.
        /// </summary>
        internal static string TrackDefaultText {
            get {
                return ResourceManager.GetString("TrackDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Економія трафіку:.
        /// </summary>
        internal static string TrafficDefaultText {
            get {
                return ResourceManager.GetString("TrafficDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибирає картинки з пісень які завантажуются під час пошуку пісень..
        /// </summary>
        internal static string TrafficToolTipDefaultText {
            get {
                return ResourceManager.GetString("TrafficToolTipDefaultText", resourceCulture);
            }
        }
    }
}
