//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Free_Spotify.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationUKR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationUKR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Free_Spotify.Localization.LocalizationUKR", typeof(LocalizationUKR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артист:.
        /// </summary>
        internal static string ArtistDefaultText {
            get {
                return ResourceManager.GetString("ArtistDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірити оновлення.
        /// </summary>
        internal static string CheckUpdatesMenuItemHeader {
            get {
                return ResourceManager.GetString("CheckUpdatesMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схоже у вас проблеми з інтернетом!.
        /// </summary>
        internal static string ErrorNoInternetText {
            get {
                return ResourceManager.GetString("ErrorNoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По запиту:.
        /// </summary>
        internal static string ErrorNothingFoundText {
            get {
                return ResourceManager.GetString("ErrorNothingFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нічого не знайдено..
        /// </summary>
        internal static string ErrorNothingFoundText1 {
            get {
                return ResourceManager.GetString("ErrorNothingFoundText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова:.
        /// </summary>
        internal static string LanguageSettingsDefaultText {
            get {
                return ResourceManager.GetString("LanguageSettingsDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що хочете послухати?.
        /// </summary>
        internal static string SearchBarTextBoxDefaultText {
            get {
                return ResourceManager.GetString("SearchBarTextBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string SettingsMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомий Артист.
        /// </summary>
        internal static string SongAuthorDefaultText {
            get {
                return ResourceManager.GetString("SongAuthorDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідомий трек.
        /// </summary>
        internal static string SongTitleDefaultText {
            get {
                return ResourceManager.GetString("SongTitleDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почніть писати щось, щоб насолоджуватися піснями!.
        /// </summary>
        internal static string TipStartWrittingText {
            get {
                return ResourceManager.GetString("TipStartWrittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трек:.
        /// </summary>
        internal static string TrackDefaultText {
            get {
                return ResourceManager.GetString("TrackDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Економія трафіку:.
        /// </summary>
        internal static string TrafficDefaultText {
            get {
                return ResourceManager.GetString("TrafficDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибирає картинки з пісень які завантажуются під час пошуку пісень..
        /// </summary>
        internal static string TrafficToolTipDefaultText {
            get {
                return ResourceManager.GetString("TrafficToolTipDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вмикати додаток коли запускається комп&apos;ютер:.
        /// </summary>
        internal static string TurnOnAppWhenWinStartDefaultText {
            get {
                return ResourceManager.GetString("TurnOnAppWhenWinStartDefaultText", resourceCulture);
            }
        }
    }
}
