//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Free_Spotify.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationRU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Free_Spotify.Localization.LocalizationRU", typeof(LocalizationRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артист:.
        /// </summary>
        internal static string ArtistDefaultText {
            get {
                return ResourceManager.GetString("ArtistDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить обновления.
        /// </summary>
        internal static string CheckUpdatesMenuItemHeader {
            get {
                return ResourceManager.GetString("CheckUpdatesMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже у вас проблемы с интернетом!.
        /// </summary>
        internal static string ErrorNoInternetText {
            get {
                return ResourceManager.GetString("ErrorNoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По запросу:.
        /// </summary>
        internal static string ErrorNothingFoundText {
            get {
                return ResourceManager.GetString("ErrorNothingFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ничего не найдено..
        /// </summary>
        internal static string ErrorNothingFoundText1 {
            get {
                return ResourceManager.GetString("ErrorNothingFoundText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string LanguageSettingsDefaultText {
            get {
                return ResourceManager.GetString("LanguageSettingsDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что хотите послушать?.
        /// </summary>
        internal static string SearchBarTextBoxDefaultText {
            get {
                return ResourceManager.GetString("SearchBarTextBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsMenuItemHeader {
            get {
                return ResourceManager.GetString("SettingsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный Автор.
        /// </summary>
        internal static string SongAuthorDefaultText {
            get {
                return ResourceManager.GetString("SongAuthorDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный Трек.
        /// </summary>
        internal static string SongTitleDefaultText {
            get {
                return ResourceManager.GetString("SongTitleDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начните писать что-то, чтобы насладится музыкой!.
        /// </summary>
        internal static string TipStartWrittingText {
            get {
                return ResourceManager.GetString("TipStartWrittingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трек:.
        /// </summary>
        internal static string TrackDefaultText {
            get {
                return ResourceManager.GetString("TrackDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экономия трафика:.
        /// </summary>
        internal static string TrafficDefaultText {
            get {
                return ResourceManager.GetString("TrafficDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убирает картинки с песен которые грузятся во время поиска песен..
        /// </summary>
        internal static string TrafficToolTipDefaultText {
            get {
                return ResourceManager.GetString("TrafficToolTipDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включать приложение при запуске компьютера:.
        /// </summary>
        internal static string TurnOnAppWhenWinStartDefaultText {
            get {
                return ResourceManager.GetString("TurnOnAppWhenWinStartDefaultText", resourceCulture);
            }
        }
    }
}
